/*
AdServer Ad Management

Testing AdsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_openapi_AdsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test AdsAPIService CreateAd", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var accountId string

		resp, httpRes, err := apiClient.AdsAPI.CreateAd(context.Background(), accountId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AdsAPIService DeleteAd", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var accountId string
		var adId string

		httpRes, err := apiClient.AdsAPI.DeleteAd(context.Background(), accountId, adId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AdsAPIService GetAd", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var accountId string
		var adId string

		resp, httpRes, err := apiClient.AdsAPI.GetAd(context.Background(), accountId, adId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AdsAPIService GetAdActiveRules", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var accountId string
		var adId string

		resp, httpRes, err := apiClient.AdsAPI.GetAdActiveRules(context.Background(), accountId, adId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AdsAPIService ListAds", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var accountId string

		resp, httpRes, err := apiClient.AdsAPI.ListAds(context.Background(), accountId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AdsAPIService PatchAd", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var accountId string
		var adId string

		resp, httpRes, err := apiClient.AdsAPI.PatchAd(context.Background(), accountId, adId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
