/*
AdServer Ad Management

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the AdsCreativeBannerFields type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AdsCreativeBannerFields{}

// AdsCreativeBannerFields Describes a banner that can be served.
type AdsCreativeBannerFields struct {
	// The HTML snippet that will be rendered.
	Snippet string `json:"snippet"`
}

// NewAdsCreativeBannerFields instantiates a new AdsCreativeBannerFields object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAdsCreativeBannerFields(snippet string) *AdsCreativeBannerFields {
	this := AdsCreativeBannerFields{}
	this.Snippet = snippet
	return &this
}

// NewAdsCreativeBannerFieldsWithDefaults instantiates a new AdsCreativeBannerFields object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAdsCreativeBannerFieldsWithDefaults() *AdsCreativeBannerFields {
	this := AdsCreativeBannerFields{}
	return &this
}

// GetSnippet returns the Snippet field value
func (o *AdsCreativeBannerFields) GetSnippet() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Snippet
}

// GetSnippetOk returns a tuple with the Snippet field value
// and a boolean to check if the value has been set.
func (o *AdsCreativeBannerFields) GetSnippetOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Snippet, true
}

// SetSnippet sets field value
func (o *AdsCreativeBannerFields) SetSnippet(v string) {
	o.Snippet = v
}

func (o AdsCreativeBannerFields) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AdsCreativeBannerFields) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["snippet"] = o.Snippet
	return toSerialize, nil
}

type NullableAdsCreativeBannerFields struct {
	value *AdsCreativeBannerFields
	isSet bool
}

func (v NullableAdsCreativeBannerFields) Get() *AdsCreativeBannerFields {
	return v.value
}

func (v *NullableAdsCreativeBannerFields) Set(val *AdsCreativeBannerFields) {
	v.value = val
	v.isSet = true
}

func (v NullableAdsCreativeBannerFields) IsSet() bool {
	return v.isSet
}

func (v *NullableAdsCreativeBannerFields) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAdsCreativeBannerFields(val *AdsCreativeBannerFields) *NullableAdsCreativeBannerFields {
	return &NullableAdsCreativeBannerFields{value: val, isSet: true}
}

func (v NullableAdsCreativeBannerFields) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAdsCreativeBannerFields) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


