/*
AdServer Ad Management

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ExchangeReviewPutFields type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ExchangeReviewPutFields{}

// ExchangeReviewPutFields `ExchangeReview` editable fields.
type ExchangeReviewPutFields struct {
	// The ID of the review to be used later when submitting bids to display the ad this review refers to.
	ExchangeReviewId string `json:"exchangeReviewId"`
	// Indicates the status of the review: * `queued`: The ad is in the exchange submission queue. * `reviewing`: The exchange has received the ad and is reviewing it. * `approved`: The exchange has reviewed the ad and approved it. * `rejected`: The exchange has reviewed the ad and rejected it. Some details of why or what can be done can be found in the `comments` field. * `revoked`: The exchange has previously reviewed and approved the ad, but the approval was revoked. Some details of why or what can be done can be found in the `comments` field.
	Status string `json:"status"`
	// Any comments that the exchange reviewer deem important.
	Comments *string `json:"comments,omitempty"`
}

// NewExchangeReviewPutFields instantiates a new ExchangeReviewPutFields object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewExchangeReviewPutFields(exchangeReviewId string, status string) *ExchangeReviewPutFields {
	this := ExchangeReviewPutFields{}
	this.ExchangeReviewId = exchangeReviewId
	this.Status = status
	return &this
}

// NewExchangeReviewPutFieldsWithDefaults instantiates a new ExchangeReviewPutFields object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewExchangeReviewPutFieldsWithDefaults() *ExchangeReviewPutFields {
	this := ExchangeReviewPutFields{}
	return &this
}

// GetExchangeReviewId returns the ExchangeReviewId field value
func (o *ExchangeReviewPutFields) GetExchangeReviewId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ExchangeReviewId
}

// GetExchangeReviewIdOk returns a tuple with the ExchangeReviewId field value
// and a boolean to check if the value has been set.
func (o *ExchangeReviewPutFields) GetExchangeReviewIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExchangeReviewId, true
}

// SetExchangeReviewId sets field value
func (o *ExchangeReviewPutFields) SetExchangeReviewId(v string) {
	o.ExchangeReviewId = v
}

// GetStatus returns the Status field value
func (o *ExchangeReviewPutFields) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *ExchangeReviewPutFields) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *ExchangeReviewPutFields) SetStatus(v string) {
	o.Status = v
}

// GetComments returns the Comments field value if set, zero value otherwise.
func (o *ExchangeReviewPutFields) GetComments() string {
	if o == nil || IsNil(o.Comments) {
		var ret string
		return ret
	}
	return *o.Comments
}

// GetCommentsOk returns a tuple with the Comments field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExchangeReviewPutFields) GetCommentsOk() (*string, bool) {
	if o == nil || IsNil(o.Comments) {
		return nil, false
	}
	return o.Comments, true
}

// HasComments returns a boolean if a field has been set.
func (o *ExchangeReviewPutFields) HasComments() bool {
	if o != nil && !IsNil(o.Comments) {
		return true
	}

	return false
}

// SetComments gets a reference to the given string and assigns it to the Comments field.
func (o *ExchangeReviewPutFields) SetComments(v string) {
	o.Comments = &v
}

func (o ExchangeReviewPutFields) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ExchangeReviewPutFields) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["exchangeReviewId"] = o.ExchangeReviewId
	toSerialize["status"] = o.Status
	if !IsNil(o.Comments) {
		toSerialize["comments"] = o.Comments
	}
	return toSerialize, nil
}

type NullableExchangeReviewPutFields struct {
	value *ExchangeReviewPutFields
	isSet bool
}

func (v NullableExchangeReviewPutFields) Get() *ExchangeReviewPutFields {
	return v.value
}

func (v *NullableExchangeReviewPutFields) Set(val *ExchangeReviewPutFields) {
	v.value = val
	v.isSet = true
}

func (v NullableExchangeReviewPutFields) IsSet() bool {
	return v.isSet
}

func (v *NullableExchangeReviewPutFields) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExchangeReviewPutFields(val *ExchangeReviewPutFields) *NullableExchangeReviewPutFields {
	return &NullableExchangeReviewPutFields{value: val, isSet: true}
}

func (v NullableExchangeReviewPutFields) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExchangeReviewPutFields) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


