/*
AdServer Ad Management

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the AdCreateFields type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AdCreateFields{}

// AdCreateFields `Ad` required fields.
type AdCreateFields struct {
	// The domain that this ad is going to redirect to.
	Domain string `json:"domain"`
	// The name of this ad.
	Name string `json:"name"`
	Spec AdsCreativeCreativeSpec `json:"spec"`
	// The rules that specify what are the conditions to display a creative group.
	Rules []AdRule `json:"rules"`
	// Tags that the user can add to facilitate searching.
	Tags []string `json:"tags,omitempty"`
}

// NewAdCreateFields instantiates a new AdCreateFields object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAdCreateFields(domain string, name string, spec AdsCreativeCreativeSpec, rules []AdRule) *AdCreateFields {
	this := AdCreateFields{}
	this.Domain = domain
	this.Name = name
	this.Spec = spec
	this.Rules = rules
	return &this
}

// NewAdCreateFieldsWithDefaults instantiates a new AdCreateFields object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAdCreateFieldsWithDefaults() *AdCreateFields {
	this := AdCreateFields{}
	return &this
}

// GetDomain returns the Domain field value
func (o *AdCreateFields) GetDomain() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Domain
}

// GetDomainOk returns a tuple with the Domain field value
// and a boolean to check if the value has been set.
func (o *AdCreateFields) GetDomainOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Domain, true
}

// SetDomain sets field value
func (o *AdCreateFields) SetDomain(v string) {
	o.Domain = v
}

// GetName returns the Name field value
func (o *AdCreateFields) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *AdCreateFields) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *AdCreateFields) SetName(v string) {
	o.Name = v
}

// GetSpec returns the Spec field value
func (o *AdCreateFields) GetSpec() AdsCreativeCreativeSpec {
	if o == nil {
		var ret AdsCreativeCreativeSpec
		return ret
	}

	return o.Spec
}

// GetSpecOk returns a tuple with the Spec field value
// and a boolean to check if the value has been set.
func (o *AdCreateFields) GetSpecOk() (*AdsCreativeCreativeSpec, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Spec, true
}

// SetSpec sets field value
func (o *AdCreateFields) SetSpec(v AdsCreativeCreativeSpec) {
	o.Spec = v
}

// GetRules returns the Rules field value
func (o *AdCreateFields) GetRules() []AdRule {
	if o == nil {
		var ret []AdRule
		return ret
	}

	return o.Rules
}

// GetRulesOk returns a tuple with the Rules field value
// and a boolean to check if the value has been set.
func (o *AdCreateFields) GetRulesOk() ([]AdRule, bool) {
	if o == nil {
		return nil, false
	}
	return o.Rules, true
}

// SetRules sets field value
func (o *AdCreateFields) SetRules(v []AdRule) {
	o.Rules = v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *AdCreateFields) GetTags() []string {
	if o == nil || IsNil(o.Tags) {
		var ret []string
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdCreateFields) GetTagsOk() ([]string, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *AdCreateFields) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given []string and assigns it to the Tags field.
func (o *AdCreateFields) SetTags(v []string) {
	o.Tags = v
}

func (o AdCreateFields) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AdCreateFields) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["domain"] = o.Domain
	toSerialize["name"] = o.Name
	toSerialize["spec"] = o.Spec
	toSerialize["rules"] = o.Rules
	if !IsNil(o.Tags) {
		toSerialize["tags"] = o.Tags
	}
	return toSerialize, nil
}

type NullableAdCreateFields struct {
	value *AdCreateFields
	isSet bool
}

func (v NullableAdCreateFields) Get() *AdCreateFields {
	return v.value
}

func (v *NullableAdCreateFields) Set(val *AdCreateFields) {
	v.value = val
	v.isSet = true
}

func (v NullableAdCreateFields) IsSet() bool {
	return v.isSet
}

func (v *NullableAdCreateFields) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAdCreateFields(val *AdCreateFields) *NullableAdCreateFields {
	return &NullableAdCreateFields{value: val, isSet: true}
}

func (v NullableAdCreateFields) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAdCreateFields) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


