/*
AdServer Ad Management

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the TimeOfWeek type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TimeOfWeek{}

// TimeOfWeek Represents a time window in a week.
type TimeOfWeek struct {
	// Indicates when the window starts in number of minutes since Sunday, midnight.
	Start float32 `json:"start"`
	// Indicates when the window ends in number of minutes since Sunday midnight, must be after `start`.
	End float32 `json:"end"`
}

// NewTimeOfWeek instantiates a new TimeOfWeek object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTimeOfWeek(start float32, end float32) *TimeOfWeek {
	this := TimeOfWeek{}
	this.Start = start
	this.End = end
	return &this
}

// NewTimeOfWeekWithDefaults instantiates a new TimeOfWeek object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTimeOfWeekWithDefaults() *TimeOfWeek {
	this := TimeOfWeek{}
	return &this
}

// GetStart returns the Start field value
func (o *TimeOfWeek) GetStart() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Start
}

// GetStartOk returns a tuple with the Start field value
// and a boolean to check if the value has been set.
func (o *TimeOfWeek) GetStartOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Start, true
}

// SetStart sets field value
func (o *TimeOfWeek) SetStart(v float32) {
	o.Start = v
}

// GetEnd returns the End field value
func (o *TimeOfWeek) GetEnd() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.End
}

// GetEndOk returns a tuple with the End field value
// and a boolean to check if the value has been set.
func (o *TimeOfWeek) GetEndOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.End, true
}

// SetEnd sets field value
func (o *TimeOfWeek) SetEnd(v float32) {
	o.End = v
}

func (o TimeOfWeek) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TimeOfWeek) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["start"] = o.Start
	toSerialize["end"] = o.End
	return toSerialize, nil
}

type NullableTimeOfWeek struct {
	value *TimeOfWeek
	isSet bool
}

func (v NullableTimeOfWeek) Get() *TimeOfWeek {
	return v.value
}

func (v *NullableTimeOfWeek) Set(val *TimeOfWeek) {
	v.value = val
	v.isSet = true
}

func (v NullableTimeOfWeek) IsSet() bool {
	return v.isSet
}

func (v *NullableTimeOfWeek) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTimeOfWeek(val *TimeOfWeek) *NullableTimeOfWeek {
	return &NullableTimeOfWeek{value: val, isSet: true}
}

func (v NullableTimeOfWeek) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTimeOfWeek) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


