/*
AdServer Ad Management

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the AdsCreativeCreativeFields type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AdsCreativeCreativeFields{}

// AdsCreativeCreativeFields Specifies editable fields that define creatives.
type AdsCreativeCreativeFields struct {
	Banner *AdsCreativeBannerFields `json:"banner,omitempty"`
}

// NewAdsCreativeCreativeFields instantiates a new AdsCreativeCreativeFields object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAdsCreativeCreativeFields() *AdsCreativeCreativeFields {
	this := AdsCreativeCreativeFields{}
	return &this
}

// NewAdsCreativeCreativeFieldsWithDefaults instantiates a new AdsCreativeCreativeFields object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAdsCreativeCreativeFieldsWithDefaults() *AdsCreativeCreativeFields {
	this := AdsCreativeCreativeFields{}
	return &this
}

// GetBanner returns the Banner field value if set, zero value otherwise.
func (o *AdsCreativeCreativeFields) GetBanner() AdsCreativeBannerFields {
	if o == nil || IsNil(o.Banner) {
		var ret AdsCreativeBannerFields
		return ret
	}
	return *o.Banner
}

// GetBannerOk returns a tuple with the Banner field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdsCreativeCreativeFields) GetBannerOk() (*AdsCreativeBannerFields, bool) {
	if o == nil || IsNil(o.Banner) {
		return nil, false
	}
	return o.Banner, true
}

// HasBanner returns a boolean if a field has been set.
func (o *AdsCreativeCreativeFields) HasBanner() bool {
	if o != nil && !IsNil(o.Banner) {
		return true
	}

	return false
}

// SetBanner gets a reference to the given AdsCreativeBannerFields and assigns it to the Banner field.
func (o *AdsCreativeCreativeFields) SetBanner(v AdsCreativeBannerFields) {
	o.Banner = &v
}

func (o AdsCreativeCreativeFields) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AdsCreativeCreativeFields) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Banner) {
		toSerialize["banner"] = o.Banner
	}
	return toSerialize, nil
}

type NullableAdsCreativeCreativeFields struct {
	value *AdsCreativeCreativeFields
	isSet bool
}

func (v NullableAdsCreativeCreativeFields) Get() *AdsCreativeCreativeFields {
	return v.value
}

func (v *NullableAdsCreativeCreativeFields) Set(val *AdsCreativeCreativeFields) {
	v.value = val
	v.isSet = true
}

func (v NullableAdsCreativeCreativeFields) IsSet() bool {
	return v.isSet
}

func (v *NullableAdsCreativeCreativeFields) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAdsCreativeCreativeFields(val *AdsCreativeCreativeFields) *NullableAdsCreativeCreativeFields {
	return &NullableAdsCreativeCreativeFields{value: val, isSet: true}
}

func (v NullableAdsCreativeCreativeFields) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAdsCreativeCreativeFields) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


