/*
AdServer Ad Management

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the AdsCreativeCreativeSpec type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AdsCreativeCreativeSpec{}

// AdsCreativeCreativeSpec Specifies the requirements for creatives.
type AdsCreativeCreativeSpec struct {
	Banner *AdsCreativeBannerSpec `json:"banner,omitempty"`
}

// NewAdsCreativeCreativeSpec instantiates a new AdsCreativeCreativeSpec object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAdsCreativeCreativeSpec() *AdsCreativeCreativeSpec {
	this := AdsCreativeCreativeSpec{}
	return &this
}

// NewAdsCreativeCreativeSpecWithDefaults instantiates a new AdsCreativeCreativeSpec object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAdsCreativeCreativeSpecWithDefaults() *AdsCreativeCreativeSpec {
	this := AdsCreativeCreativeSpec{}
	return &this
}

// GetBanner returns the Banner field value if set, zero value otherwise.
func (o *AdsCreativeCreativeSpec) GetBanner() AdsCreativeBannerSpec {
	if o == nil || IsNil(o.Banner) {
		var ret AdsCreativeBannerSpec
		return ret
	}
	return *o.Banner
}

// GetBannerOk returns a tuple with the Banner field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdsCreativeCreativeSpec) GetBannerOk() (*AdsCreativeBannerSpec, bool) {
	if o == nil || IsNil(o.Banner) {
		return nil, false
	}
	return o.Banner, true
}

// HasBanner returns a boolean if a field has been set.
func (o *AdsCreativeCreativeSpec) HasBanner() bool {
	if o != nil && !IsNil(o.Banner) {
		return true
	}

	return false
}

// SetBanner gets a reference to the given AdsCreativeBannerSpec and assigns it to the Banner field.
func (o *AdsCreativeCreativeSpec) SetBanner(v AdsCreativeBannerSpec) {
	o.Banner = &v
}

func (o AdsCreativeCreativeSpec) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AdsCreativeCreativeSpec) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Banner) {
		toSerialize["banner"] = o.Banner
	}
	return toSerialize, nil
}

type NullableAdsCreativeCreativeSpec struct {
	value *AdsCreativeCreativeSpec
	isSet bool
}

func (v NullableAdsCreativeCreativeSpec) Get() *AdsCreativeCreativeSpec {
	return v.value
}

func (v *NullableAdsCreativeCreativeSpec) Set(val *AdsCreativeCreativeSpec) {
	v.value = val
	v.isSet = true
}

func (v NullableAdsCreativeCreativeSpec) IsSet() bool {
	return v.isSet
}

func (v *NullableAdsCreativeCreativeSpec) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAdsCreativeCreativeSpec(val *AdsCreativeCreativeSpec) *NullableAdsCreativeCreativeSpec {
	return &NullableAdsCreativeCreativeSpec{value: val, isSet: true}
}

func (v NullableAdsCreativeCreativeSpec) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAdsCreativeCreativeSpec) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


