/*
AdServer Creative Management

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the CreativeSpec type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreativeSpec{}

// CreativeSpec Specifies the requirements for creatives.
type CreativeSpec struct {
	Banner *BannerSpec `json:"banner,omitempty"`
}

// NewCreativeSpec instantiates a new CreativeSpec object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreativeSpec() *CreativeSpec {
	this := CreativeSpec{}
	return &this
}

// NewCreativeSpecWithDefaults instantiates a new CreativeSpec object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreativeSpecWithDefaults() *CreativeSpec {
	this := CreativeSpec{}
	return &this
}

// GetBanner returns the Banner field value if set, zero value otherwise.
func (o *CreativeSpec) GetBanner() BannerSpec {
	if o == nil || IsNil(o.Banner) {
		var ret BannerSpec
		return ret
	}
	return *o.Banner
}

// GetBannerOk returns a tuple with the Banner field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreativeSpec) GetBannerOk() (*BannerSpec, bool) {
	if o == nil || IsNil(o.Banner) {
		return nil, false
	}
	return o.Banner, true
}

// HasBanner returns a boolean if a field has been set.
func (o *CreativeSpec) HasBanner() bool {
	if o != nil && !IsNil(o.Banner) {
		return true
	}

	return false
}

// SetBanner gets a reference to the given BannerSpec and assigns it to the Banner field.
func (o *CreativeSpec) SetBanner(v BannerSpec) {
	o.Banner = &v
}

func (o CreativeSpec) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreativeSpec) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Banner) {
		toSerialize["banner"] = o.Banner
	}
	return toSerialize, nil
}

type NullableCreativeSpec struct {
	value *CreativeSpec
	isSet bool
}

func (v NullableCreativeSpec) Get() *CreativeSpec {
	return v.value
}

func (v *NullableCreativeSpec) Set(val *CreativeSpec) {
	v.value = val
	v.isSet = true
}

func (v NullableCreativeSpec) IsSet() bool {
	return v.isSet
}

func (v *NullableCreativeSpec) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreativeSpec(val *CreativeSpec) *NullableCreativeSpec {
	return &NullableCreativeSpec{value: val, isSet: true}
}

func (v NullableCreativeSpec) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreativeSpec) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


