/*
AdServer Creative Management

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the CreativeGroupCreateFields type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreativeGroupCreateFields{}

// CreativeGroupCreateFields `CreativeGroup` required fields.
type CreativeGroupCreateFields struct {
	// The domain that this creative group is going to redirect to.
	Domain string `json:"domain"`
	// The name of the creative group.
	Name string `json:"name"`
	Spec CreativeSpec `json:"spec"`
	// A list of all creatives that compose this creative group with their relative weights.
	Creatives []WeightedCreative `json:"creatives"`
	// Tags that the user can add to facilitate searching.
	Tags []string `json:"tags,omitempty"`
}

// NewCreativeGroupCreateFields instantiates a new CreativeGroupCreateFields object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreativeGroupCreateFields(domain string, name string, spec CreativeSpec, creatives []WeightedCreative) *CreativeGroupCreateFields {
	this := CreativeGroupCreateFields{}
	this.Domain = domain
	this.Name = name
	this.Spec = spec
	this.Creatives = creatives
	return &this
}

// NewCreativeGroupCreateFieldsWithDefaults instantiates a new CreativeGroupCreateFields object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreativeGroupCreateFieldsWithDefaults() *CreativeGroupCreateFields {
	this := CreativeGroupCreateFields{}
	return &this
}

// GetDomain returns the Domain field value
func (o *CreativeGroupCreateFields) GetDomain() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Domain
}

// GetDomainOk returns a tuple with the Domain field value
// and a boolean to check if the value has been set.
func (o *CreativeGroupCreateFields) GetDomainOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Domain, true
}

// SetDomain sets field value
func (o *CreativeGroupCreateFields) SetDomain(v string) {
	o.Domain = v
}

// GetName returns the Name field value
func (o *CreativeGroupCreateFields) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreativeGroupCreateFields) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreativeGroupCreateFields) SetName(v string) {
	o.Name = v
}

// GetSpec returns the Spec field value
func (o *CreativeGroupCreateFields) GetSpec() CreativeSpec {
	if o == nil {
		var ret CreativeSpec
		return ret
	}

	return o.Spec
}

// GetSpecOk returns a tuple with the Spec field value
// and a boolean to check if the value has been set.
func (o *CreativeGroupCreateFields) GetSpecOk() (*CreativeSpec, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Spec, true
}

// SetSpec sets field value
func (o *CreativeGroupCreateFields) SetSpec(v CreativeSpec) {
	o.Spec = v
}

// GetCreatives returns the Creatives field value
func (o *CreativeGroupCreateFields) GetCreatives() []WeightedCreative {
	if o == nil {
		var ret []WeightedCreative
		return ret
	}

	return o.Creatives
}

// GetCreativesOk returns a tuple with the Creatives field value
// and a boolean to check if the value has been set.
func (o *CreativeGroupCreateFields) GetCreativesOk() ([]WeightedCreative, bool) {
	if o == nil {
		return nil, false
	}
	return o.Creatives, true
}

// SetCreatives sets field value
func (o *CreativeGroupCreateFields) SetCreatives(v []WeightedCreative) {
	o.Creatives = v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *CreativeGroupCreateFields) GetTags() []string {
	if o == nil || IsNil(o.Tags) {
		var ret []string
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreativeGroupCreateFields) GetTagsOk() ([]string, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *CreativeGroupCreateFields) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given []string and assigns it to the Tags field.
func (o *CreativeGroupCreateFields) SetTags(v []string) {
	o.Tags = v
}

func (o CreativeGroupCreateFields) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreativeGroupCreateFields) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["domain"] = o.Domain
	toSerialize["name"] = o.Name
	toSerialize["spec"] = o.Spec
	toSerialize["creatives"] = o.Creatives
	if !IsNil(o.Tags) {
		toSerialize["tags"] = o.Tags
	}
	return toSerialize, nil
}

type NullableCreativeGroupCreateFields struct {
	value *CreativeGroupCreateFields
	isSet bool
}

func (v NullableCreativeGroupCreateFields) Get() *CreativeGroupCreateFields {
	return v.value
}

func (v *NullableCreativeGroupCreateFields) Set(val *CreativeGroupCreateFields) {
	v.value = val
	v.isSet = true
}

func (v NullableCreativeGroupCreateFields) IsSet() bool {
	return v.isSet
}

func (v *NullableCreativeGroupCreateFields) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreativeGroupCreateFields(val *CreativeGroupCreateFields) *NullableCreativeGroupCreateFields {
	return &NullableCreativeGroupCreateFields{value: val, isSet: true}
}

func (v NullableCreativeGroupCreateFields) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreativeGroupCreateFields) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


