/*
AdServer Creative Management

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the CreativeCreateFieldsAllOfBanner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreativeCreateFieldsAllOfBanner{}

// CreativeCreateFieldsAllOfBanner Specifies the banner.
type CreativeCreateFieldsAllOfBanner struct {
	// The width of the banner in pixels.
	Width float32 `json:"width"`
	// The height of the banner in pixels.
	Height float32 `json:"height"`
	// The HTML snippet that will be rendered.
	Snippet string `json:"snippet"`
}

// NewCreativeCreateFieldsAllOfBanner instantiates a new CreativeCreateFieldsAllOfBanner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreativeCreateFieldsAllOfBanner(width float32, height float32, snippet string) *CreativeCreateFieldsAllOfBanner {
	this := CreativeCreateFieldsAllOfBanner{}
	this.Width = width
	this.Height = height
	this.Snippet = snippet
	return &this
}

// NewCreativeCreateFieldsAllOfBannerWithDefaults instantiates a new CreativeCreateFieldsAllOfBanner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreativeCreateFieldsAllOfBannerWithDefaults() *CreativeCreateFieldsAllOfBanner {
	this := CreativeCreateFieldsAllOfBanner{}
	return &this
}

// GetWidth returns the Width field value
func (o *CreativeCreateFieldsAllOfBanner) GetWidth() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Width
}

// GetWidthOk returns a tuple with the Width field value
// and a boolean to check if the value has been set.
func (o *CreativeCreateFieldsAllOfBanner) GetWidthOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Width, true
}

// SetWidth sets field value
func (o *CreativeCreateFieldsAllOfBanner) SetWidth(v float32) {
	o.Width = v
}

// GetHeight returns the Height field value
func (o *CreativeCreateFieldsAllOfBanner) GetHeight() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Height
}

// GetHeightOk returns a tuple with the Height field value
// and a boolean to check if the value has been set.
func (o *CreativeCreateFieldsAllOfBanner) GetHeightOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Height, true
}

// SetHeight sets field value
func (o *CreativeCreateFieldsAllOfBanner) SetHeight(v float32) {
	o.Height = v
}

// GetSnippet returns the Snippet field value
func (o *CreativeCreateFieldsAllOfBanner) GetSnippet() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Snippet
}

// GetSnippetOk returns a tuple with the Snippet field value
// and a boolean to check if the value has been set.
func (o *CreativeCreateFieldsAllOfBanner) GetSnippetOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Snippet, true
}

// SetSnippet sets field value
func (o *CreativeCreateFieldsAllOfBanner) SetSnippet(v string) {
	o.Snippet = v
}

func (o CreativeCreateFieldsAllOfBanner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreativeCreateFieldsAllOfBanner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["width"] = o.Width
	toSerialize["height"] = o.Height
	toSerialize["snippet"] = o.Snippet
	return toSerialize, nil
}

type NullableCreativeCreateFieldsAllOfBanner struct {
	value *CreativeCreateFieldsAllOfBanner
	isSet bool
}

func (v NullableCreativeCreateFieldsAllOfBanner) Get() *CreativeCreateFieldsAllOfBanner {
	return v.value
}

func (v *NullableCreativeCreateFieldsAllOfBanner) Set(val *CreativeCreateFieldsAllOfBanner) {
	v.value = val
	v.isSet = true
}

func (v NullableCreativeCreateFieldsAllOfBanner) IsSet() bool {
	return v.isSet
}

func (v *NullableCreativeCreateFieldsAllOfBanner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreativeCreateFieldsAllOfBanner(val *CreativeCreateFieldsAllOfBanner) *NullableCreativeCreateFieldsAllOfBanner {
	return &NullableCreativeCreateFieldsAllOfBanner{value: val, isSet: true}
}

func (v NullableCreativeCreateFieldsAllOfBanner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreativeCreateFieldsAllOfBanner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


